// Albarán / proof-of-visit PDF generation (pdfkit + qrcode). One tenant-branded, single-page
// A4 document per visit. Shared by both auth surfaces that can download it — the
// session-authenticated platform (routes/visits.js) and the API-key connector
// (routes/connect.js) — same split as the photo proxy each of those already has.
//
// Font: pdfkit's built-in Helvetica/Times/Courier are WinAnsi-only and render Cyrillic as
// garbage boxes/mojibake. We embed static Noto Sans (Regular + Bold, Cyrillic+Latin subset,
// src/server/assets/fonts/) instead, so Ukrainian (and any Latin-Extended) text renders
// correctly next to Spanish/English on the same page.
// Localization: every static label goes through Lp(lang, key) — the tenant's PDF language
// follows the same `bot_lang` setting used for the Telegram bot (es | en | uk).
const path = require("path");
const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");

const INK = "#1b1a16", DIM = "#6b665b", LINE = "#d5cfbf";

const FONT_DIR = path.join(__dirname, "assets", "fonts");
const FONT_REGULAR = path.join(FONT_DIR, "NotoSans-Regular.ttf");
const FONT_BOLD = path.join(FONT_DIR, "NotoSans-Bold.ttf");

// ── Labels (es / en / uk) ───────────────────────────────────────────────────────
const PDF_T = {
  point:        { es: "Punto de visita", en: "Point of visit", uk: "Точка візиту" },
  execution:    { es: "Ejecución", en: "Execution", uk: "Виконання" },
  worker:       { es: "Trabajador", en: "Worker", uk: "Працівник" },
  checkin:      { es: "Check-in", en: "Check-in", uk: "Чек-ін" },
  checkout:     { es: "Check-out", en: "Check-out", uk: "Чек-аут" },
  duration:     { es: "Duración", en: "Duration", uk: "Тривалість" },
  gps:          { es: "Coordenadas GPS", en: "GPS coordinates", uk: "GPS-координати" },
  comment:      { es: "Comentario del trabajador", en: "Worker comment", uk: "Коментар працівника" },
  noComment:    { es: "— sin comentario —", en: "— no comment —", uk: "— без коментаря —" },
  voiceNote:    { es: "🎙️ Nota de voz adjunta (disponible en la plataforma).", en: "🎙️ Voice note attached (available in the platform).", uk: "🎙️ Додано голосове повідомлення (доступне в платформі)." },
  photos:       { es: "Fotos del check-in", en: "Check-in photos", uk: "Фото чек-іну" },
  signature:    { es: "Firma del cliente / Client signature", en: "Client signature", uk: "Підпис клієнта" },
  verify:       { es: "Verificar", en: "Verify", uk: "Перевірити" },
  generated:    { es: "Generado", en: "Generated", uk: "Згенеровано" },
  docTitle:     { es: "Albarán de Visita", en: "Visit Delivery Note", uk: "Накладна візиту" },
  footnote:     { es: "Documento generado automáticamente por StarX como justificante de visita.",
                  en: "Document automatically generated by StarX as proof of visit.",
                  uk: "Документ автоматично згенеровано StarX як підтвердження візиту." },
  taxId:        { es: "CIF/NIF", en: "Tax ID", uk: "ІПН" },
};
function Lp(lang, key) {
  const row = PDF_T[key];
  if (!row) return key;
  return row[lang] || row.es;
}

function fmtDateTime(ts, lang) {
  if (!ts) return "—";
  const locale = lang === "en" ? "en-GB" : lang === "uk" ? "uk-UA" : "es-ES";
  try { return new Date(ts).toLocaleString(locale, { dateStyle: "short", timeStyle: "short" }); }
  catch { return String(ts); }
}
// Round a raw GPS coordinate string/number to 5 decimal places (~1.1 m precision) —
// stored coordinates can carry many more digits than are meaningful on a printed document.
function roundCoord(v) {
  const n = parseFloat(v);
  return isFinite(n) ? n.toFixed(5) : (v || "—");
}
// Human duration between two ISO timestamps (mirrors the client's durationText()).
function durationText(startIso, endIso) {
  const a = Date.parse(startIso), b = Date.parse(endIso);
  if (!isFinite(a) || !isFinite(b) || b < a) return "—";
  const min = Math.round((b - a) / 60000);
  if (min < 60) return min + " min";
  return Math.floor(min / 60) + " h " + (min % 60) + " min";
}

// Resolve one of the visit's stored photos to raw bytes, same logic as the photo-proxy
// routes (Telegram file_id for bot check-ins, Supabase Storage ref for PWA ones). Best
// effort: a photo that fails to resolve is just skipped rather than failing the whole PDF.
async function fetchPhotoBuffer(source, visit, idx) {
  const ids = String(visit.photoFileIds || "").split(",").map(s => s.trim()).filter(Boolean);
  const ref = ids[idx];
  if (!ref) return null;
  try {
    if (visit.source === "pwa") {
      const photo = await source.getPhoto(ref);
      return photo ? photo.buffer : null;
    }
    const link = await require("./bot/manager").fileLink(ref);
    const tg = await fetch(link);
    if (!tg.ok) return null;
    return Buffer.from(await tg.arrayBuffer());
  } catch (e) { return null; }
}

// Render the Albarán straight into `res` as a streamed PDF response.
//   visit       — the stored Visit record
//   point       — the matching Point record, if still found (may be null)
//   tenant      — the owning tenant (name used as a fallback company name)
//   pdfSettings — { pdfCompanyName, pdfTaxId, pdfAddress, pdfLogoUrl, pdfDocTitle, pdfFootnote }
//   source      — this tenant's bound datasource (for photo lookups)
//   baseUrl     — origin used to build the verification QR link
//   lang        — "es" | "en" | "uk" — the tenant's configured document language
async function renderVisitPdf(res, { visit, point, tenant, pdfSettings, source, baseUrl, lang }) {
  pdfSettings = pdfSettings || {};
  lang = ["es", "en", "uk"].includes(lang) ? lang : "es";
  const docId = `ALB-${new Date(visit.timestamp || Date.now()).getFullYear()}-${visit.visitId}`;
  const title = pdfSettings.pdfDocTitle || Lp(lang, "docTitle");

  res.set("Content-Type", "application/pdf");
  res.set("Content-Disposition", `attachment; filename="${docId}.pdf"`);

  const doc = new PDFDocument({ size: "A4", margin: 40 });
  doc.registerFont("Body", FONT_REGULAR);
  doc.registerFont("Body-Bold", FONT_BOLD);
  doc.pipe(res);

  // ── Header: logo + legal details on the left, doc title + ID + date on the right ──
  // Both columns start at the SAME y (40) and share the same row heights, so the title
  // block stays vertically centered against the company block even when one wraps.
  const HEAD_Y = 40, LEFT_W = 250, RIGHT_X = 300, RIGHT_W = 255;
  let textX = 40;
  if (pdfSettings.pdfLogoUrl) {
    try {
      const r = await fetch(pdfSettings.pdfLogoUrl);
      if (r.ok) {
        const buf = Buffer.from(await r.arrayBuffer());
        doc.image(buf, 40, HEAD_Y, { fit: [64, 64] });
        textX = 114;
      }
    } catch (e) { /* logo is optional — skip on any fetch/format failure */ }
  }
  doc.fillColor(INK).fontSize(15).font("Body-Bold").text(pdfSettings.pdfCompanyName || tenant.name || "—", textX, HEAD_Y, { width: LEFT_W - (textX - 40) });
  doc.fontSize(8.5).font("Body").fillColor(DIM);
  if (pdfSettings.pdfTaxId) doc.text(Lp(lang, "taxId") + ": " + pdfSettings.pdfTaxId, textX, doc.y + 2, { width: LEFT_W - (textX - 40) });
  if (pdfSettings.pdfAddress) doc.text(pdfSettings.pdfAddress, textX, doc.y + 1, { width: LEFT_W - (textX - 40) });

  doc.fontSize(15).font("Body-Bold").fillColor(INK).text(title, RIGHT_X, HEAD_Y, { width: RIGHT_W, align: "right" });
  doc.fontSize(8.5).font("Body").fillColor(DIM)
    .text(docId, RIGHT_X, HEAD_Y + 20, { width: RIGHT_W, align: "right" })
    .text(Lp(lang, "generated") + ": " + fmtDateTime(new Date().toISOString(), lang), RIGHT_X, HEAD_Y + 32, { width: RIGHT_W, align: "right" });

  // Rule sits below whichever column grew taller (address can wrap to 2 lines).
  const ruleY = Math.max(doc.y + 10, HEAD_Y + 78);
  doc.moveTo(40, ruleY).lineTo(555, ruleY).strokeColor(LINE).lineWidth(1).stroke();

  // ── Target point ──
  let y = ruleY + 14;
  doc.fontSize(10.5).font("Body-Bold").fillColor(INK).text(Lp(lang, "point"), 40, y);
  y += 15;
  doc.fontSize(10).font("Body").fillColor(INK).text((point && (point.name || point.id)) || visit.pointName || visit.pointId || "—", 40, y);
  y = doc.y + 2;
  doc.fontSize(8.5).fillColor(DIM).text((point && point.address) || "—", 40, y);
  y = doc.y + 16;

  // ── Execution metadata ──
  doc.fontSize(10.5).font("Body-Bold").fillColor(INK).text(Lp(lang, "execution"), 40, y);
  y += 15;
  const rows = [[Lp(lang, "worker"), visit.workerName || visit.workerTelegramId || "—"], [Lp(lang, "checkin"), fmtDateTime(visit.timestamp, lang)]];
  if (visit.checkoutAt) {
    rows.push([Lp(lang, "checkout"), fmtDateTime(visit.checkoutAt, lang)]);
    rows.push([Lp(lang, "duration"), durationText(visit.timestamp, visit.checkoutAt)]);
  }
  rows.push([Lp(lang, "gps"), (visit.lat && visit.lng) ? `${roundCoord(visit.lat)}, ${roundCoord(visit.lng)}` : "—"]);
  rows.forEach(([k, v]) => {
    doc.fontSize(8.5).font("Body-Bold").fillColor(DIM).text(k, 40, y, { continued: true, width: 130 });
    doc.font("Body").fillColor(INK).text("   " + v);
    y += 13;
  });
  y += 12;

  // ── Notes / work done ──
  doc.fontSize(10.5).font("Body-Bold").fillColor(INK).text(Lp(lang, "comment"), 40, y);
  y += 16;
  const noteText = String(visit.note || "").indexOf("🎙️voice:") === 0
    ? Lp(lang, "voiceNote")
    : (visit.note || Lp(lang, "noComment"));
  // A light box with real padding around the comment text (was flush against the margin).
  const commentBoxH = 40;
  doc.roundedRect(40, y, 515, commentBoxH, 5).strokeColor(LINE).lineWidth(1).stroke();
  doc.fontSize(9).font("Body").fillColor(INK)
    .text(noteText, 52, y + 10, { width: 491, height: commentBoxH - 18, ellipsis: true });
  y += commentBoxH + 16;

  // ── Photos (GPS/timestamp stamped as an overlay bar) ──
  const photoCount = Number(visit.photoCount) || 0;
  if (photoCount) {
    doc.fontSize(10.5).font("Body-Bold").fillColor(INK).text(Lp(lang, "photos"), 40, y);
    y += 16;
    const thumbW = 158, thumbH = 108, gap = 15;
    let x = 40;
    for (let i = 0; i < Math.min(photoCount, 3); i++) {
      const buf = await fetchPhotoBuffer(source, visit, i);
      if (buf) {
        try {
          // A hairline frame + consistent padding around each thumbnail, instead of photos
          // sitting flush against each other and the overlay bar touching the image edge.
          doc.roundedRect(x, y, thumbW, thumbH, 4).strokeColor(LINE).lineWidth(1).stroke();
          doc.image(buf, x + 3, y + 3, { fit: [thumbW - 6, thumbH - 6], align: "center", valign: "center" });
          doc.rect(x + 3, y + thumbH - 18, thumbW - 6, 15).fillOpacity(0.62).fillColor("#000").fill();
          doc.fillOpacity(1).fontSize(6.2).font("Body").fillColor("#fff")
            .text(`${roundCoord(visit.lat)}, ${roundCoord(visit.lng)} · ${fmtDateTime(visit.timestamp, lang)}`, x + 8, y + thumbH - 15, { width: thumbW - 16 });
        } catch (e) { /* a photo that fails to embed is just skipped */ }
      }
      x += thumbW + gap;
    }
    y += thumbH + 18;
  }

  // ── Verification QR + signature box (fixed near the bottom to keep this one page) ──
  const boxY = Math.max(y, 690);
  const verifyUrl = `${baseUrl}/verify/${encodeURIComponent(tenant.id)}/${encodeURIComponent(visit.visitId)}`;
  doc.roundedRect(40, boxY, 340, 76, 5).strokeColor(LINE).lineWidth(1).stroke();
  doc.fontSize(8).font("Body").fillColor(DIM).text(Lp(lang, "signature"), 52, boxY + 10);
  try {
    const qrDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 0, width: 76 });
    doc.image(Buffer.from(qrDataUrl.split(",")[1], "base64"), 470, boxY, { width: 76, height: 76 });
    doc.fontSize(6.5).font("Body").fillColor(DIM).text(Lp(lang, "verify"), 470, boxY + 78, { width: 76, align: "center" });
  } catch (e) { /* QR is a nice-to-have, never block the document on it */ }

  doc.fontSize(7.2).font("Body").fillColor(DIM)
    .text(pdfSettings.pdfFootnote || Lp(lang, "footnote"), 40, boxY + 92, { width: 515, align: "center" });

  doc.end();
}

module.exports = { renderVisitPdf };
